server:
  port: 8080

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  pool_size: 20
  min_idle_conns: 5

mysql:
  dsn: "root:123456@tcp(localhost:3306)/douyin?charset=utf8mb4&parseTime=True&loc=Local"
  max_idle_conn: 20
  max_open_conn: 100

consul:
  address: "localhost:8500"
  check_ttl: "15s"         # 服务健康检查间隔
  deregister_after: "3m"  # 异常服务保留时间

jwt:
  secret: "douyin_ecom_2023"  # 至少32位随机字符串
  expire_hours: 72            # 令牌有效期
  issuer: "douyin.auth.service" # 签发机构标识

service:
  ip: "127.0.0.1"  # 显式指定本机IP
  user_http_port: 8080        # HTTP服务端口
  user_rpc_port: 8880    # RPC服务端口
  product_http_port: 8081        # HTTP服务端口
  product_rpc_port: 8881    # RPC服务端口  
  cart_http_port: 8082        # HTTP服务端口
  cart_rpc_port: 8882    # RPC服务端口  
  order_http_port: 8083        # HTTP服务端口
  order_rpc_port: 8883    # RPC服务端口  
  payment_http_port: 8084        # HTTP服务端口
  payment_rpc_port: 8884    # RPC服务端口


whitelist:
  - "/login"
  - "/register"
  - "/health"

blacklist:
  - "/admin"
